### ISSUE TITLE
Build Fails During Copy Pod Resources

### ISSUE THREAD

**Issue by barrettj** [PTEz/LumberjackConsole#1]
When including this via CocoaPods my builds will fail during the copy pod resources step.  Removing this pod fixes the problem.  Anyone experienced this before?

The reference to iOS 6 is strange, as I'm targeting iOS 7

warning: Internationalization of /Users/barrettjacobsen/Programming/Cocoa/Attainment/GoBook/Pods/LumberjackConsole/Source/Adjust Levels/PTEAdjustLevelsCell.xib is not available when compiling for targets before iOS 6.0
ibtool --reference-external-strings-file --errors --warnings --notices --output-format human-readable-text --compile /Users/barrettjacobsen/Library/Developer/Xcode/DerivedData/GoBook-ejopxiyfqzxpdmazibxblkgkyxol/Build/Products/Debug-iphonesimulator/GoBook.app/PTEDashboard.nib /Users/barrettjacobsen/Programming/Cocoa/Attainment/GoBook/Pods/LumberjackConsole/Source/PTEDashboard.xib --sdk /Applications/Xcode51-Beta5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk
Command /bin/sh failed with exit code 255

**Comment by Whirlwind** [comment]
Same problem. Xcode 8.3.1 and Xcode 9 Beta 3

**Comment by rivera-ernesto** [comment]
Please give 3.3.0 a try.
