### ISSUE TITLE
Unable to see log inside the console window in iOS application.

### ISSUE THREAD

**Issue by parvezq** [PTEz/LumberjackConsole#14]
Really a very good UI component for viewing logs.

I have added this component in an iOS application via cocoapods with below entries:
`
pod 'CocoaLumberjack'
pod 'LumberjackConsole', '2.4.3', :configurations => ['Debug']
pod 'NBULog'
`

Also the initialisation code is as given below:
`
[PTEDashboard.sharedDashboard show];
DDLogInfo(@"Added console dashboard");
`

 The log files are being created in documents directory as I have changed the default directory path to Documents directory when setting up DDFileLogger. I am able to see the logs being created. The log level is verbose. I am not able to see the log entries in the console window. Am I missing any other step while using this component ?

Thanks

**Comment by HHK1** [comment]
Are you using iOS 10? I didn't have any issues before, but now the console window is empty.

**Comment by qureship786** [comment]
I haven't tried it on any iOS deviceyet nor run it using iOS 10. I tried it on iphone 6s plus simulator. The deployment target for the application is iOS 8.0. The base sdk used to compile the project is iOS 9.3. The file logger code setup in AppDelegate is:

`
-(DDFileLogger*)generateDDFileLogger{
    DDFileLogger *result = nil;
    NSString* docDirPath = DOC_DIR_PATH;
    DDLogFileManagerDefault* defaultManager = [[DDLogFileManagerDefault alloc] initWithLogsDirectory:docDirPath];
    
    result = [[DDFileLogger alloc] initWithLogFileManager:defaultManager];
    result.rollingFrequency = 60 * 60 * 24; // 24 hour rolling
    result.maximumFileSize = (1024 * 1024)*5; // 5 MB
    result.logFileManager.maximumNumberOfLogFiles = kMaximumNoOfLogFiles;//indicates one week logging.
    return result;
}
`

where DOC_DIR_PATH is:
`
[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0]
`

Did you see any issue in above code ? If No then what will be the possible reason for it ?

Thanks

**Comment by qureship786** [comment]
Heny, did you get a chance to look into the above mentioned issue ?

Thanks

**Comment by HHK1** [comment]
My issue was related to iOS 10 and has been fixed since with this commit https://github.com/PTEz/LumberjackConsole/commit/9f5c7d7a29e6a1157ee3af1f7e1609b568f3b4b1

**Comment by parvezq** [comment]
Have you tried it with a file logger (DDFileLogger) ? Can you mention the steps to use the console with a file logger ?

**Comment by rivera-ernesto** [comment]
Please give 3.3.0 a try.
