### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by sibljon** [PTEz/LumberjackConsole#2]
It's my opinion (and I believe that this opinion is shared by others as well) that 3rd party libraries should not have dependencies themselves, wherever possible. Obviously, for `LumberjackConsole`, `CocoaLumberjack` is a required dependency. However, `NBUCore` does not seem to add anything other than convenience methods. This means that any project that would like to `LumberjackConsole` must also inherit the extra cruft of `NBUCore`.

I do really appreciate that you open sourced this project to begin with, and I accept the likelihood that it wasn't worth your effort to decouple the `NBUCore` dependency. I just thought I'd provide some hopefully constructive feedback as to why I won't be including it in my project after all.

**Comment by johndpope** [comment]
related - https://github.com/CyberAgent/NBULog/issues/7
