### ISSUE TITLE
Support for Swift CocoaLumberjack Pod dependency

### ISSUE THREAD

**Issue by LeonidKokhnovich** [PTEz/LumberjackConsole#23]
Hi! Thank you for a great tool! 
I wanted to check if it's possible to support Swift CocoaLumberjack available as a Pod using 'CocoaLumberjack/Swift' reference? This is the how CocoaLumberjack suggests referencing the module from Swift projects:
```
platform :ios, '8.0'

# You need to set target when you use CocoaPods 1.0.0 or later.
target 'SampleTarget' do
  use_frameworks!
  pod 'CocoaLumberjack/Swift'
end
```

Currently, LumberjackConsole is using Pod 'CocoaLumberjack'.

In my app, there are other libraries that also reference 'CocoaLumberjack/Swift' Pod, so having the console to point to the 'CocoaLumberjack' Pod introduces problems with dependency tree. 
I wonder if we could have a fix for that or maybe you could point to some workarounds?

Thank you!

**Comment by rivera-ernesto** [comment]
If this project works with `CocoaLumberjack/Swift`, then feel free to Pull Request it.

You can test it by forking the project, modifying the podspec, and then add `git: <YourFork>` to test it.
