### ISSUE TITLE
Hard to open console from status bar on iPhone X

### ISSUE THREAD

**Issue by LeonidKokhnovich** [PTEz/LumberjackConsole#27]
Hi! 
Thanks for supporting such a great project.
We are having issues with opening/dismissing log console on iPhone X device from the status bar because the button is too small and it's covered partly behind the screen curve.
Is there a way to make it more accessible on such devices (use safe area only, increase button size)?

**Comment by rivera-ernesto** [comment]
I (or anyone who wants to contribute) have yet to rework this. It really is an open issue.

**Comment by rivera-ernesto** [comment]
Please try just released 3.6.0.
