### ISSUE TITLE
Would be nice to have `hide` function the same as `show`

### ISSUE THREAD

**Issue by serluca** [PTEz/LumberjackConsole#9]
Hi Ernesto 

Great job I love it.
I added your console as a component in the app, so all my team have access to the console if they want pressing on a button.
Is there any way to close the console in the same way?

**Comment by rivera-ernesto** [comment]
For you can only expand/minimize it. How would you show it back once hidden?

Feel free to come up with some ideas so we can merge them back to the project.

**Comment by rivera-ernesto** [comment]
Exists since 3.0.1.
